fake_activities = [
    {
        "id": 1,
        "name": "Morning Run",
        "sport_type": "Run",
        "distance_km": 8.2,
        "moving_time_minutes": 45,
        "average_pace": "5:29/km",
        "average_heartrate": 154,
        "max_heartrate": 176,
        "total_elevation_gain": 42.0,
        "strava_url": "https://www.strava.com/activities/1",
    },
    {
        "id": 2,
        "name": "Evening Ride",
        "sport_type": "Ride",
        "distance_km": 32.5,
        "moving_time_minutes": 78,
        "average_pace": "24.9 km/h",
        "average_heartrate": 142,
        "max_heartrate": 168,
        "total_elevation_gain": 310.0,
        "strava_url": "https://www.strava.com/activities/2",
    },
]